FROM node:latest

# Install dependencies
RUN apt-get update
RUN apt-get install groff less python python-dev python-setuptools jq -y
RUN easy_install pip

RUN pip install docker-compose

# Install AWS CLI
RUN pip install awscli


# Install Docker
RUN apt-get install apt-transport-https ca-certificates curl software-properties-common -y
RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
RUN add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
#RUN add-apt-repository "deb [arch=armhf] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
#RUN add-apt-repository "deb [arch=s390x] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
RUN apt-get update
RUN apt-get install docker.io -y


# Clean up
RUN apt-get clean